### PR TITLE
[feat] Edit and pin notes feature added

### PR DESCRIPTION
**Pull request by rishichourasia**
## Features to check - 
1. Edit note
2. Pin notes

### CODE REVIEW

**Review by rahul31agrawal — APPROVED** [review]
Hi Rishi,
code structure looks neat
UI looks awesome
looks good to merge

**Comment by rishichourasia** [comment]
> 

yes thanks rahul for the review

**Review by athar05 — COMMENTED** [review]
The code looks clean. Good job

**Comment by athar05** [comment]
I really liked the UI. Very close to Google's note taking app. Would also love to see the dark version of your app.

**Pull request merged**
